<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ai_translate"
 *
 * Auto generated by Extension Builder 2018-04-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'AI Translate',
    'description' => 'This extension provides option to translate content element, and tca record texts using deepl,google,open ai and gemini.',
    'category' => 'module',
    'author' => 'PIT Solutions',
    'author_email' => 'contact@pitsolutions.com',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '2.1.0',
    'constraints' => [
        'depends' => [
            'typo3' => '11.0.0-11.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
