<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ai_translate"
 *
 * Auto generated by Extension Builder 2024-04-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Ai Translate',
    'description' => 'This extension provides option to translate content element, and tca record texts to Deepl, Google, OpenAI, Gemini and Cohere supported languages.',
    'category' => 'module',
    'author' => 'PIT Solutions',
    'author_email' => 'contact@pitsolutions.com',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '4.0.3',
    'constraints' => [
        'depends' => [
            'typo3' => '13.0.0-13.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
