<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ai_translate"
 *
 * Auto generated by Extension Builder 2024-04-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Ai Translate',
    'description' => 'AI Translate brings fast, flexible translation directly into the TYPO3 backend. Translate content elements and TCA records automatically using leading AI and translation services - including Google Translate, DeepL, OpenAI (ChatGPT), Gemini, Claude and Cohere. Editors can auto-detect source language or select languages manually, making it a powerful auto translate and language translation solution for multilingual TYPO3 websites',
    'category' => 'module',
    'author' => 'PIT Solutions',
    'author_email' => 'contact@pitsolutions.com',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '4.0.4',
    'constraints' => [
        'depends' => [
            'typo3' => '13.0.0-13.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
